package edu.nyu.cs.javagit.client.cli;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import edu.nyu.cs.javagit.api.JavaGitConfiguration;
import edu.nyu.cs.javagit.api.JavaGitException;
import edu.nyu.cs.javagit.api.commands.CommandResponse;
import edu.nyu.cs.javagit.client.IGitFetch;
import edu.nyu.cs.javagit.utilities.CheckUtilities;

public class CliGitFetch implements IGitFetch
{

    public void fetch(File repoDirectory)
            throws JavaGitException, IOException
    {
        CheckUtilities.checkFileValidity(repoDirectory);
        GitFetchParser parser = new GitFetchParser();
        List<String> command = buildCommand(repoDirectory);
        ProcessUtilities.runCommand(repoDirectory,
                command, parser);
        //if (response.containsError()) {
        //	throw new JavaGitException(418001, "Git Init error");
        //}
    }

    /*
      * Build the command to be executed using the Git Init method
      */
    private List<String> buildCommand(File repoDirectory)
    {
        List<String> command = new ArrayList<String>();
        command.add(JavaGitConfiguration.getGitCommand());
        command.add("fetch");
        return command;
    }

    /**
     * Parser class to parse the output generated by git init and return a
     * <code>GitInitResponse</code> object.
     */
    public class GitFetchParser implements IParser
    {

        public void parseLine(String line)
        {
            //To change body of implemented methods use File | Settings | File Templates.
        }

        public void processExitCode(int code)
        {
            //To change body of implemented methods use File | Settings | File Templates.
        }

        public CommandResponse getResponse() throws JavaGitException
        {
            return null;  //To change body of implemented methods use File | Settings | File Templates.
        }
    }
}